
-- TABLA HOTEL
CREATE TABLE HOTEL (
    id_hotel        INTEGER      NOT NULL,
    nombre          CHAR(50),
    ciudad          CHAR(50),
    pais            CHAR(50),
    telefono        INTEGER,
    correo_electronico VARCHAR2(100),
    CONSTRAINT HOTEL_PK PRIMARY KEY (id_hotel)
);

-- TABLA CLIENTE:
CREATE TABLE CLIENTE (
    id_reserva      INTEGER      NOT NULL,
    nombre_completo VARCHAR2(100),
    genero          CHAR(10),
    fecha_nacimiento INTEGER,
    nacionalidad    CHAR(50),
    estado_civil    CHAR(20),
    telefono        INTEGER,
    correo_electronico VARCHAR2(100),
    direccion       VARCHAR2(150),
    comuna          CHAR(50),
    ciudad          CHAR(50),
    pais            CHAR(50),
    CLIENTE_ID      NUMBER NOT NULL,
    HOTEL_HOTEL_ID  NUMBER NOT NULL,
    CONSTRAINT CLIENTE_PK PRIMARY KEY (CLIENTE_ID),
    CONSTRAINT CLIENTE_HOTEL_FK FOREIGN KEY (HOTEL_HOTEL_ID)
    REFERENCES HOTEL(id_hotel)
);

-- TABLA RESERVA:
CREATE TABLE RESERVA (
    id_reserva      INTEGER      NOT NULL,
    fecha_reserva   INTEGER,
    fecha_de_llegada INTEGER,
    fecha_de_salida  INTEGER,
    cantidad_de_dias INTEGER,
    RESERVA_ID      NUMBER NOT NULL,
    CLIENTE_CLIENTE_ID NUMBER NOT NULL,
    CONSTRAINT RESERVA_PK PRIMARY KEY (RESERVA_ID),
    CONSTRAINT RESERVA_CLIENTE_FK FOREIGN KEY (CLIENTE_CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
);

-- TABLA HABITACIÓN:
CREATE TABLE HABITACION (
    HABITACION_ID   NUMBER NOT NULL,
    id_numero_habitacion INTEGER NOT NULL,
    tipo            CHAR(20),
    cama            CHAR(20),
    HOTEL_HOTEL_ID  NUMBER NOT NULL,
    RESERVA_HABITACION_RESERVA_HABITACION_ID NUMBER,
    CONSTRAINT HABITACION_PK PRIMARY KEY (HABITACION_ID),
    CONSTRAINT HABITACION_HOTEL_FK FOREIGN KEY (HOTEL_HOTEL_ID)
    REFERENCES HOTEL(id_hotel)
);

-- Tabla RESERVA_HABITACION:
CREATE TABLE RESERVA_HABITACION (
    id_numero_reserva   INTEGER NOT NULL,
    id_numero_habitacion INTEGER NOT NULL,
    RESERVA_HABITACION_ID NUMBER NOT NULL,
    CONSTRAINT RESERVA_HABITACION_PK PRIMARY KEY (RESERVA_HABITACION_ID)
);


-- TABLA HABITACION SIMPLE:
CREATE TABLE HABITACION_SIMPLE (
    HABITACION_HABITACION_ID NUMBER NOT NULL,
    numero_de_camas INTEGER,
    CONSTRAINT HABITACION_SIMPLE_PK PRIMARY KEY (HABITACION_HABITACION_ID),
    CONSTRAINT HABITACION_SIMPLE_FK FOREIGN KEY (HABITACION_HABITACION_ID)
    REFERENCES HABITACION(HABITACION_ID)
);

-- TABLA HABITACION DOBLE
CREATE TABLE HABITACION_DOBLE (
    HABITACION_HABITACION_ID NUMBER NOT NULL,
    tipo_de_cama CHAR(20),
    CONSTRAINT HABITACION_DOBLE_PK PRIMARY KEY (HABITACION_HABITACION_ID),
    CONSTRAINT HABITACION_DOBLE_FK FOREIGN KEY (HABITACION_HABITACION_ID)
    REFERENCES HABITACION(HABITACION_ID)
);
